# Generated by Django 2.2.5 on 2019-09-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='modified_at',
            new_name='modification_date',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='followed_id',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='follower_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
