# Generated by Django 2.2.5 on 2019-09-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190912_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_place',
            field=models.CharField(max_length=75, null=True, verbose_name='Birth place'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='User description'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
