# Generated by Django 2.2.5 on 2019-10-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190928_1152'),
        ('users', '0004_auto_20190929_1229'),
    ]

    operations = [
    ]
