# Generated by Django 2.2.5 on 2019-10-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20191004_2303'),
        ('users', '0005_merge_20191004_0852'),
        ('users', '0005_merge_20191004_2335'),
    ]

    operations = [
    ]
