# Generated by Django 2.2.5 on 2019-10-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20191007_1917'),
        ('users', '0005_merge_20191007_1946'),
    ]

    operations = [
    ]
