# Generated by Django 2.2.5 on 2019-10-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20191009_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_user',
            field=models.URLField(blank=True, null=True, verbose_name='User Picture'),
        ),
    ]
