# Generated by Django 2.2.5 on 2019-10-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20191008_2259'),
        ('users', '0007_profile_image_user'),
    ]

    operations = [
    ]
