# Generated by Django 2.2.5 on 2019-10-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20191012_1101'),
        ('users', '0006_merge_20191007_2242'),
    ]

    operations = [
    ]
