# Generated by Django 2.2.5 on 2019-09-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190912_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='response_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='Response to'),
        ),
    ]
