# Generated by Django 2.2.5 on 2019-09-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20190916_1936'),
        ('articles', '0005_auto_20190914_2315'),
    ]

    operations = [
    ]
