# Generated by Django 2.2.5 on 2019-09-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_merge_20190918_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='state',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published')], default='DR', max_length=2, verbose_name='Article state'),
        ),
    ]
