# Generated by Django 2.2.5 on 2019-09-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_merge_20190918_2005'),
        ('articles', '0012_auto_20190917_1907'),
    ]

    operations = [
    ]
