# Generated by Django 2.2.5 on 2019-09-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_merge_20190918_2030'),
        ('articles', '0013_auto_20190920_1221'),
    ]

    operations = [
    ]
