# Generated by Django 2.2.5 on 2019-09-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_merge_20190922_1153'),
        ('articles', '0014_merge_20190922_2243'),
        ('articles', '0011_merge_20190918_1840'),
    ]

    operations = [
    ]
