# Generated by Django 2.2.5 on 2019-09-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_merge_20190918_1840'),
        ('articles', '0015_auto_20190923_2053'),
        ('articles', '0014_merge_20190922_1153'),
        ('articles', '0014_merge_20190922_2243'),
    ]

    operations = [
    ]
