# Generated by Django 2.2.5 on 2019-10-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_merge_20190925_1930'),
        ('articles', '0014_merge_20190921_1236'),
    ]

    operations = [
    ]
