# Generated by Django 2.2.5 on 2019-09-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_merge_20190921_1236'),
        ('articles', '0016_merge_20190925_1930'),
    ]

    operations = [
    ]
