# Generated by Django 2.2.5 on 2019-10-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_favorite'),
        ('articles', '0017_merge_20191001_2231'),
    ]

    operations = [
    ]
