# Generated by Django 2.2.5 on 2019-10-04 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_favorite'),
        ('articles', '0017_merge_20190928_1152'),
    ]

    operations = [
    ]
