# Generated by Django 2.2.5 on 2019-10-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_merge_20190928_1152'),
        ('articles', '0019_merge_20191002_1916'),
    ]

    operations = [
    ]
