# Generated by Django 2.2.5 on 2019-10-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_merge_20191004_2335'),
        ('articles', '0019_merge_20191004_2303'),
        ('articles', '0019_merge_20191004_0852'),
    ]

    operations = [
    ]
