# Generated by Django 2.2.5 on 2019-10-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_merge_20191009_1212'),
        ('articles', '0020_merge_20191008_2259'),
    ]

    operations = [
    ]
