version: '3'

services:
  django:
    build: .
    container_name: django-project
    volumes:
      - .:/django-project
#    restart: always
#    env_file:
#     - main/.env
    ports:
      - "80:8000"